### ISSUE TITLE
Add sample length offset

### ISSUE THREAD

**Issue by djhocking** [Regional-Fish-Modeling/Regional_Trend_Model#1]
Need to add offset for sample length. Will first have to get this for the data then add it to the model and data prep scripts.

**Comment by ykanno** [comment]
My bad. Sorry. Thanks for catching it.

On Fri, Jun 24, 2016 at 3:02 PM, Daniel J. Hocking <notifications@github.com

**Comment by djhocking** [comment]
Need to get the stream length from the original data and not that currently in the repo.

**Comment by djhocking** [comment]
Done
